# Generated by Django 4.0.3 on 2023-05-24 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0002_alter_post_post_created_alter_post_post_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 16, 11, 21, 961351)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_edited',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 16, 11, 21, 961419)),
        ),
    ]
