# Generated by Django 4.0.3 on 2023-05-24 16:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PostApp', '0004_alter_post_post_created_alter_post_post_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 16, 39, 32, 204888)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_edited',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 16, 39, 32, 204957)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
