# Generated by Django 4.0.3 on 2023-05-24 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0005_alter_post_post_created_alter_post_post_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='comment_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 16, 59, 28, 42761)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 16, 59, 28, 41291)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_edited',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 16, 59, 28, 41366)),
        ),
    ]
